"""Add custom_data column to agent calls

Revision ID: 0665ca29a27d
Revises: b359868218eb
Create Date: 2026-07-13 16:45:58.455068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0665ca29a27d'
down_revision: Union[str, None] = 'b359868218eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retell_calls', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.alter_column('retell_calls', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'registered'::character varying"))
    op.alter_column('retell_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('retell_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_retell_calls_application_id'), table_name='retell_calls')
    op.drop_index(op.f('idx_retell_calls_retell_call_id'), table_name='retell_calls')
    op.create_index(op.f('ix_retell_calls_application_id'), 'retell_calls', ['application_id'], unique=False)
    op.create_index(op.f('ix_retell_calls_retell_call_id'), 'retell_calls', ['retell_call_id'], unique=False)
    op.add_column('vapi_calls', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.alter_column('vapi_configurations', 'agent_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'vapi'::character varying"))
    op.alter_column('vapi_configurations', 'first_speaker',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('vapi_configurations', 'retell_responsiveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('vapi_configurations', 'retell_interruption_sensitivity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('vapi_configurations', 'retell_voicemail_detection',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('vapi_configurations', 'retell_ivr_hangup',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('vapi_configurations', 'retell_end_call_on_silence_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('600000'))
    op.alter_column('vapi_configurations', 'retell_max_call_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3600000'))
    op.alter_column('vapi_configurations', 'retell_ring_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('30000'))
    op.alter_column('vapi_configurations', 'retell_boosted_keywords',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vapi_configurations', 'retell_boosted_keywords',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('vapi_configurations', 'retell_ring_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('30000'))
    op.alter_column('vapi_configurations', 'retell_max_call_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3600000'))
    op.alter_column('vapi_configurations', 'retell_end_call_on_silence_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('600000'))
    op.alter_column('vapi_configurations', 'retell_ivr_hangup',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('vapi_configurations', 'retell_voicemail_detection',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('vapi_configurations', 'retell_interruption_sensitivity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('vapi_configurations', 'retell_responsiveness',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('vapi_configurations', 'first_speaker',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('vapi_configurations', 'agent_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'vapi'::character varying"))
    op.drop_column('vapi_calls', 'custom_data')
    op.drop_index(op.f('ix_retell_calls_retell_call_id'), table_name='retell_calls')
    op.drop_index(op.f('ix_retell_calls_application_id'), table_name='retell_calls')
    op.create_index(op.f('idx_retell_calls_retell_call_id'), 'retell_calls', ['retell_call_id'], unique=False)
    op.create_index(op.f('idx_retell_calls_application_id'), 'retell_calls', ['application_id'], unique=False)
    op.alter_column('retell_calls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('retell_calls', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('retell_calls', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'registered'::character varying"))
    op.drop_column('retell_calls', 'custom_data')
    # ### end Alembic commands ###
