"""Add custom_data column to agent calls

Revision ID: 0665ca29a27d
Revises: b359868218eb
Create Date: 2026-07-13 16:45:58.455068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0665ca29a27d'
down_revision: Union[str, None] = 'b359868218eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retell_calls',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('application_id', sa.String(length=36), nullable=False),
        sa.Column('retell_call_id', sa.String(length=100), nullable=False),
        sa.Column('web_call_url', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False, server_default=sa.text("'registered'::character varying")),
        sa.Column('transcript', sa.Text(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('recording_url', sa.Text(), nullable=True),
        sa.Column('custom_data', sa.JSON(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('cost', sa.Float(), nullable=True),
        sa.Column('disconnection_reason', sa.String(length=100), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('user_sentiment', sa.String(length=50), nullable=True),
        sa.Column('call_successful', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retell_calls_application_id'), 'retell_calls', ['application_id'], unique=False)
    op.create_index(op.f('ix_retell_calls_retell_call_id'), 'retell_calls', ['retell_call_id'], unique=False)
    op.add_column('vapi_calls', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.add_column('vapi_configurations', sa.Column('agent_provider', sa.String(length=50), nullable=False, server_default='vapi'))
    op.add_column('vapi_configurations', sa.Column('retell_llm_id', sa.String(length=255), nullable=True))
    op.add_column('vapi_configurations', sa.Column('retell_agent_id', sa.String(length=255), nullable=True))
    op.add_column('vapi_configurations', sa.Column('first_speaker', sa.String(length=20), nullable=False, server_default='ai'))
    op.add_column('vapi_configurations', sa.Column('retell_responsiveness', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('vapi_configurations', sa.Column('retell_interruption_sensitivity', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('vapi_configurations', sa.Column('retell_voicemail_detection', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('vapi_configurations', sa.Column('retell_ivr_hangup', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('vapi_configurations', sa.Column('retell_end_call_on_silence_ms', sa.Integer(), nullable=False, server_default='600000'))
    op.add_column('vapi_configurations', sa.Column('retell_max_call_duration_ms', sa.Integer(), nullable=False, server_default='3600000'))
    op.add_column('vapi_configurations', sa.Column('retell_ring_duration_ms', sa.Integer(), nullable=False, server_default='30000'))
    op.add_column('vapi_configurations', sa.Column('retell_boosted_keywords', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vapi_configurations', 'retell_boosted_keywords')
    op.drop_column('vapi_configurations', 'retell_ring_duration_ms')
    op.drop_column('vapi_configurations', 'retell_max_call_duration_ms')
    op.drop_column('vapi_configurations', 'retell_end_call_on_silence_ms')
    op.drop_column('vapi_configurations', 'retell_ivr_hangup')
    op.drop_column('vapi_configurations', 'retell_voicemail_detection')
    op.drop_column('vapi_configurations', 'retell_interruption_sensitivity')
    op.drop_column('vapi_configurations', 'retell_responsiveness')
    op.drop_column('vapi_configurations', 'first_speaker')
    op.drop_column('vapi_configurations', 'retell_agent_id')
    op.drop_column('vapi_configurations', 'retell_llm_id')
    op.drop_column('vapi_configurations', 'agent_provider')
    op.drop_column('vapi_calls', 'custom_data')
    op.drop_index(op.f('ix_retell_calls_retell_call_id'), table_name='retell_calls')
    op.drop_index(op.f('ix_retell_calls_application_id'), table_name='retell_calls')
    op.drop_table('retell_calls')
    # ### end Alembic commands ###
