"""add retell opt out sensitive data and fallback voice id

Revision ID: 490d936ed6af
Revises: 0665ca29a27d
Create Date: 2026-07-13 22:46:47.711390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490d936ed6af'
down_revision: Union[str, None] = '0665ca29a27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vapi_configurations', sa.Column('retell_opt_out_sensitive_data_storage', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('vapi_configurations', sa.Column('retell_fallback_voice_id', sa.String(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vapi_configurations', 'retell_fallback_voice_id')
    op.drop_column('vapi_configurations', 'retell_opt_out_sensitive_data_storage')
    # ### end Alembic commands ###
