"""add_vapi_advanced_settings_and_job_prompts

Revision ID: ad9ecfd2e38f
Revises: 0018_edu_history
Create Date: 2026-07-08 17:58:57.274708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9ecfd2e38f'
down_revision: Union[str, None] = '0018_edu_history'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('vapi_prompt', sa.Text(), nullable=True))
    op.add_column('vapi_configurations', sa.Column('transcriber_language', sa.String(length=50), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_background_denoising', sa.Boolean(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_confidence_threshold', sa.Float(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_keyterms', sa.Text(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_end_of_turn_confidence', sa.Float(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_min_end_of_turn_silence', sa.Integer(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_max_turn_silence', sa.Integer(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_smart_endpointing', sa.Boolean(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_fallback_provider', sa.String(length=100), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_fallback_language', sa.String(length=50), nullable=False))
    op.add_column('vapi_configurations', sa.Column('transcriber_fallback_model', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vapi_configurations', 'transcriber_fallback_model')
    op.drop_column('vapi_configurations', 'transcriber_fallback_language')
    op.drop_column('vapi_configurations', 'transcriber_fallback_provider')
    op.drop_column('vapi_configurations', 'transcriber_smart_endpointing')
    op.drop_column('vapi_configurations', 'transcriber_max_turn_silence')
    op.drop_column('vapi_configurations', 'transcriber_min_end_of_turn_silence')
    op.drop_column('vapi_configurations', 'transcriber_end_of_turn_confidence')
    op.drop_column('vapi_configurations', 'transcriber_keyterms')
    op.drop_column('vapi_configurations', 'transcriber_confidence_threshold')
    op.drop_column('vapi_configurations', 'transcriber_background_denoising')
    op.drop_column('vapi_configurations', 'transcriber_language')
    op.drop_column('jobs', 'vapi_prompt')
    # ### end Alembic commands ###
