"""Add VapiCall model

Revision ID: b359868218eb
Revises: ce99dbce7ab0
Create Date: 2026-07-08 21:11:47.740350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b359868218eb'
down_revision: Union[str, None] = 'ce99dbce7ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vapi_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=100), nullable=False),
    sa.Column('web_call_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vapi_calls_application_id'), 'vapi_calls', ['application_id'], unique=False)
    op.create_index(op.f('ix_vapi_calls_vapi_call_id'), 'vapi_calls', ['vapi_call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vapi_calls_vapi_call_id'), table_name='vapi_calls')
    op.drop_index(op.f('ix_vapi_calls_application_id'), table_name='vapi_calls')
    op.drop_table('vapi_calls')
    # ### end Alembic commands ###
