"""add_llm_voice_advanced_settings

Revision ID: ce99dbce7ab0
Revises: ad9ecfd2e38f
Create Date: 2026-07-08 18:05:59.537479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce99dbce7ab0'
down_revision: Union[str, None] = 'ad9ecfd2e38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vapi_configurations', sa.Column('llm_temperature', sa.Float(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('llm_max_tokens', sa.Integer(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('llm_emotion_recognition_enabled', sa.Boolean(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('llm_num_fast_turns', sa.Integer(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('voice_speed', sa.Float(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('voice_stability', sa.Float(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('voice_similarity_boost', sa.Float(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('voice_optimize_streaming_latency', sa.Integer(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('voice_filler_injection_enabled', sa.Boolean(), nullable=False))
    op.add_column('vapi_configurations', sa.Column('voice_background_sound', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vapi_configurations', 'voice_background_sound')
    op.drop_column('vapi_configurations', 'voice_filler_injection_enabled')
    op.drop_column('vapi_configurations', 'voice_optimize_streaming_latency')
    op.drop_column('vapi_configurations', 'voice_similarity_boost')
    op.drop_column('vapi_configurations', 'voice_stability')
    op.drop_column('vapi_configurations', 'voice_speed')
    op.drop_column('vapi_configurations', 'llm_num_fast_turns')
    op.drop_column('vapi_configurations', 'llm_emotion_recognition_enabled')
    op.drop_column('vapi_configurations', 'llm_max_tokens')
    op.drop_column('vapi_configurations', 'llm_temperature')
    # ### end Alembic commands ###
